# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ubuntu:20.10

pipelines:
  default:
    - step:
        script:
          # Print the Linux version.
          #- echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
          - export TERM=linux
          - echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
          - uname -a
          # Print the gcc version.
          - apt-get update -y
          - apt install build-essential -y
          - gcc --version
          - apt-get install -y -q libjack-jackd2-dev
          - apt-get install -y -q libsndfile1-dev -y -q
          - wget https://cmake.org/files/v3.18/cmake-3.18.0-rc1-Linux-x86_64.tar.gz
          - tar xf cmake-3.18.0-rc1-Linux-x86_64.tar.gz
          - export PATH="`pwd`/cmake-3.18.0-rc1-Linux-x86_64/bin:$PATH"
          # Print the CMake version.
          - cmake --version
          #- git submodule update --init
          #- mkdir build
          #- cd build
          #- echo "Trying to build"
          # Call the CMake.
          #- cmake ..
          # Build the project.
          #- make
