# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ubuntu:bionic

pipelines:
  default:
    - step:
        script:
          # Print the Linux version.
          - uname -a
          # Print the gcc version.
          - apt-get update -qq
          - apt install build-essential -y
          - gcc --version
          - apt-get install software-properties-common -y
          # Add PPA repository.
          - echo 'deb http://ppa.launchpad.net/george-edison55/cmake-3.x/ubuntu trusty main' | tee -a /etc/apt/sources.list.d/cmake.list
          - apt-get update -qq
          - apt-get install cmake -y --force-yes
          # Print the CMake version.
          - cmake --version
          #- git submodule update --init
          #- mkdir build
          #- cd build
          #- echo "Trying to build"
          # Call the CMake.
          #- cmake ..
          # Build the project.
          #- make
